name: Multiple Jobs

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Successful command
       run: echo "Hello"
     - name: Run on success
       if:${{ success() }}
       run: echo "Previous steps succeeded"
     - name: Run on failure
       if: ${{ failure() }}
       run: echo "Something failed"
     - name: Always execute
       if: ${{always() }}
       run: echo "Cleanup/reporting step"
