name: Share Files Between Jobs

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create File
        run: echo "hello" > demo.txt

      - name: Upload File
        uses: actions/upload-artifact@v4
        with:
          name: demo-file
          path: demo.txt


  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download File
        uses: actions/download-artifact@v5
        with:
          name: demo-file

      - name: Read File
        run: cat demo.txt
